"""retirar alt.housing_index, duplicado por realestate

Las dos tablas estaban a cero filas y sin ningun fetcher que las
alimentara. El concepto lo cubre `realestate.price_index` y
`realestate.price_index_value`, que si tienen datos: 85 indices de 41
paises via BIS y OCDE.

Revision ID: 1df48aa663ea
Revises: 9c02eb906bdd
Create Date: 2026-08-06 10:43:35.916391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1df48aa663ea'
down_revision: Union[str, Sequence[str], None] = '9c02eb906bdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('housing_index_value', schema='alt')
    op.drop_index(op.f('ix_alt_housing_country'), table_name='housing_index', schema='alt')
    op.drop_table('housing_index', schema='alt')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('housing_index',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('country_code', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('index_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['country_code'], ['ref.country.code'], name=op.f('housing_index_country_code_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('housing_index_pkey')),
    sa.UniqueConstraint('code', name=op.f('housing_index_code_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='alt'
    )
    op.create_index(op.f('ix_alt_housing_country'), 'housing_index', ['country_code'], unique=False, schema='alt')
    op.create_table('housing_index_value',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('index_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('value', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=False),
    sa.Column('yoy_change_pct', sa.NUMERIC(precision=8, scale=4), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['index_id'], ['alt.housing_index.id'], name=op.f('housing_index_value_index_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('housing_index_value_pkey')),
    sa.UniqueConstraint('index_id', 'date', name=op.f('housing_index_value_index_id_date_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='alt'
    )
    # ### end Alembic commands ###
