"""indices FK restantes en deriv, fi y macro

Revision ID: e91bf635ef50
Revises: 6009fb7b9807
Create Date: 2026-08-03 22:10:25.057960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e91bf635ef50'
down_revision: Union[str, Sequence[str], None] = '6009fb7b9807'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_deriv_fut_source', 'futures_daily', ['source_id'], unique=False, schema='deriv')
    op.create_index('ix_deriv_vol_source', 'volatility_daily', ['source_id'], unique=False, schema='deriv')
    op.create_index('ix_fi_yc_source', 'yield_curve', ['source_id'], unique=False, schema='fi')
    op.create_index('ix_macro_indsrc_source', 'indicator_source', ['source_id'], unique=False, schema='macro')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_macro_indsrc_source', table_name='indicator_source', schema='macro')
    op.drop_index('ix_fi_yc_source', table_name='yield_curve', schema='fi')
    op.drop_index('ix_deriv_vol_source', table_name='volatility_daily', schema='deriv')
    op.drop_index('ix_deriv_fut_source', table_name='futures_daily', schema='deriv')
    # ### end Alembic commands ###
