"""nuevas fuentes: COT, LEI, factores, prima riesgo, realestate, calendar

Revision ID: 8d89ac814aba
Revises: e645e3e14db2
Create Date: 2026-08-03 23:14:25.835944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d89ac814aba'
down_revision: Union[str, Sequence[str], None] = 'e645e3e14db2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # El esquema realestate estaba declarado en stonks.db.SCHEMAS
    # pero nunca se creo en la base de datos.
    op.execute("CREATE SCHEMA IF NOT EXISTS realestate")
    op.execute("CREATE SCHEMA IF NOT EXISTS calendar")
    op.create_table('cot_contract',
    sa.Column('code', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('exchange', sa.String(length=20), nullable=True),
    sa.Column('commodity_group', sa.String(length=60), nullable=True),
    sa.Column('commodity_subgroup', sa.String(length=80), nullable=True),
    sa.Column('contract_units', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('code'),
    schema='deriv'
    )
    op.create_index('ix_deriv_cot_grupo', 'cot_contract', ['commodity_group'], unique=False, schema='deriv')
    op.create_table('release',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('country_code', sa.String(length=3), nullable=True),
    sa.Column('agency', sa.String(length=200), nullable=True),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_code'], ['ref.country.code'], ),
    sa.ForeignKeyConstraint(['source_id'], ['meta.data_source.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'external_id'),
    schema='calendar'
    )
    op.create_index('ix_cal_release_country', 'release', ['country_code'], unique=False, schema='calendar')
    op.create_table('cot_report',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('contract_code', sa.String(length=12), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('open_interest', sa.BigInteger(), nullable=True),
    sa.Column('comm_long', sa.BigInteger(), nullable=True),
    sa.Column('comm_short', sa.BigInteger(), nullable=True),
    sa.Column('noncomm_long', sa.BigInteger(), nullable=True),
    sa.Column('noncomm_short', sa.BigInteger(), nullable=True),
    sa.Column('noncomm_spread', sa.BigInteger(), nullable=True),
    sa.Column('nonrept_long', sa.BigInteger(), nullable=True),
    sa.Column('nonrept_short', sa.BigInteger(), nullable=True),
    sa.Column('traders_total', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contract_code'], ['deriv.cot_contract.code'], ),
    sa.ForeignKeyConstraint(['source_id'], ['meta.data_source.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_code', 'report_date'),
    schema='deriv'
    )
    op.create_index('ix_deriv_cot_fecha', 'cot_report', ['report_date'], unique=False, schema='deriv')
    op.create_index('ix_deriv_cot_source', 'cot_report', ['source_id'], unique=False, schema='deriv')
    op.create_table('factor_return',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('region', sa.String(length=20), nullable=False),
    sa.Column('frequency', sa.String(length=10), nullable=False),
    sa.Column('factor', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('value_pct', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['meta.data_source.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region', 'frequency', 'factor', 'date'),
    schema='equity'
    )
    op.create_index('ix_eq_factor_date', 'factor_return', ['date'], unique=False, schema='equity')
    op.create_table('country_risk_premium',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.String(length=3), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('equity_risk_premium', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('country_risk_premium', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('default_spread', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('moodys_rating', sa.String(length=10), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_code'], ['ref.country.code'], ),
    sa.ForeignKeyConstraint(['source_id'], ['meta.data_source.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_code', 'year'),
    schema='fi'
    )
    op.create_index('ix_fi_crp_year', 'country_risk_premium', ['year'], unique=False, schema='fi')
    op.create_table('price_index',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('country_code', sa.String(length=3), nullable=True),
    sa.Column('segment', sa.String(length=20), nullable=True),
    sa.Column('measure', sa.String(length=20), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=True),
    sa.Column('base_period', sa.String(length=20), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_code'], ['ref.country.code'], ),
    sa.ForeignKeyConstraint(['source_id'], ['meta.data_source.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='realestate'
    )
    op.create_index('ix_re_index_country', 'price_index', ['country_code'], unique=False, schema='realestate')
    op.create_table('legal_entity',
    sa.Column('lei', sa.String(length=20), nullable=False),
    sa.Column('legal_name', sa.String(length=500), nullable=False),
    sa.Column('country_code', sa.String(length=3), nullable=True),
    sa.Column('legal_jurisdiction', sa.String(length=10), nullable=True),
    sa.Column('entity_status', sa.String(length=20), nullable=True),
    sa.Column('entity_category', sa.String(length=40), nullable=True),
    sa.Column('parent_lei', sa.String(length=20), nullable=True),
    sa.Column('registration_status', sa.String(length=30), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['country_code'], ['ref.country.code'], ),
    sa.PrimaryKeyConstraint('lei'),
    schema='ref'
    )
    op.create_index('ix_ref_lei_country', 'legal_entity', ['country_code'], unique=False, schema='ref')
    op.create_index('ix_ref_lei_name', 'legal_entity', ['legal_name'], unique=False, schema='ref')
    op.create_table('release_date',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('release_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('is_scheduled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['release_id'], ['calendar.release.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('release_id', 'date'),
    schema='calendar'
    )
    op.create_index('ix_cal_reldate_date', 'release_date', ['date'], unique=False, schema='calendar')
    op.create_table('price_index_value',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('index_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('is_forecast', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['index_id'], ['realestate.price_index.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('index_id', 'date'),
    schema='realestate'
    )
    op.create_index('ix_re_value_index_date', 'price_index_value', ['index_id', 'date'], unique=False, schema='realestate')
    op.add_column('company', sa.Column('lei', sa.String(length=20), nullable=True), schema='equity')
    op.create_index('ix_eq_company_lei', 'company', ['lei'], unique=False, schema='equity')
    op.create_foreign_key(None, 'company', 'legal_entity', ['lei'], ['lei'], source_schema='equity', referent_schema='ref')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'company', schema='equity', type_='foreignkey')
    op.drop_index('ix_eq_company_lei', table_name='company', schema='equity')
    op.drop_column('company', 'lei', schema='equity')
    op.drop_index('ix_re_value_index_date', table_name='price_index_value', schema='realestate')
    op.drop_table('price_index_value', schema='realestate')
    op.drop_index('ix_cal_reldate_date', table_name='release_date', schema='calendar')
    op.drop_table('release_date', schema='calendar')
    op.drop_index('ix_ref_lei_name', table_name='legal_entity', schema='ref')
    op.drop_index('ix_ref_lei_country', table_name='legal_entity', schema='ref')
    op.drop_table('legal_entity', schema='ref')
    op.drop_index('ix_re_index_country', table_name='price_index', schema='realestate')
    op.drop_table('price_index', schema='realestate')
    op.drop_index('ix_fi_crp_year', table_name='country_risk_premium', schema='fi')
    op.drop_table('country_risk_premium', schema='fi')
    op.drop_index('ix_eq_factor_date', table_name='factor_return', schema='equity')
    op.drop_table('factor_return', schema='equity')
    op.drop_index('ix_deriv_cot_source', table_name='cot_report', schema='deriv')
    op.drop_index('ix_deriv_cot_fecha', table_name='cot_report', schema='deriv')
    op.drop_table('cot_report', schema='deriv')
    op.drop_index('ix_cal_release_country', table_name='release', schema='calendar')
    op.drop_table('release', schema='calendar')
    op.drop_index('ix_deriv_cot_grupo', table_name='cot_contract', schema='deriv')
    op.drop_table('cot_contract', schema='deriv')
    # ### end Alembic commands ###
