"""integridad: ref.area, FK comercio, is_forecast e indices FK

Revision ID: 6009fb7b9807
Revises: 495f24976494
Create Date: 2026-08-03 22:01:05.835271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6009fb7b9807'
down_revision: Union[str, Sequence[str], None] = '495f24976494'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Codigos no ISO que usan las fuentes de comercio (WITS, UN Comtrade,
# IMF DOTS) como declarante o socio. Sin ellos, trade.flow no puede
# tener FK y el socio comercial queda sin validar.
# (codigo, nombre, tipo, pais_sucesor)
AREAS_NO_ISO = [
    # --- Agregados regionales y categorias especiales ---
    ("WLD", "Mundo (todos los paises)", "aggregate", None),
    ("EAS", "Asia Oriental y Pacifico", "aggregate", None),
    ("ECS", "Europa y Asia Central", "aggregate", None),
    ("LCN", "America Latina y Caribe", "aggregate", None),
    ("MEA", "Oriente Medio y Norte de Africa", "aggregate", None),
    ("NAC", "America del Norte", "aggregate", None),
    ("SAS", "Asia Meridional", "aggregate", None),
    ("SSF", "Africa Subsahariana", "aggregate", None),
    ("OAS", "Otros paises de Asia, no especificados", "aggregate", None),
    ("UNS", "Areas no especificadas", "aggregate", None),
    ("SPE", "Categorias especiales", "aggregate", None),
    ("FRE", "Zonas francas", "aggregate", None),
    ("BUN", "Combustible y provisiones de barcos (bunkers)",
     "aggregate", None),
    # --- Entidades historicas, con su pais sucesor cuando es univoco ---
    ("CSK", "Checoslovaquia (disuelta en 1993)", "historical", None),
    ("DDR", "Republica Democratica Alemana (hasta 1990)",
     "historical", "DEU"),
    ("YUG", "Yugoslavia (disuelta en 1992)", "historical", None),
    ("SVU", "Union Sovietica (disuelta en 1991)", "historical", None),
    ("YDR", "Yemen del Sur (unificado en 1990)", "historical", "YEM"),
    ("ANT", "Antillas Neerlandesas (disueltas en 2010)",
     "historical", None),
    ("BLX", "Union Economica Belgo-Luxemburguesa", "historical", None),
    ("ETF", "Etiopia incluyendo Eritrea (hasta 1993)",
     "historical", "ETH"),
    ("ZAR", "Zaire (hoy Rep. Dem. del Congo)", "historical", "COD"),
    ("ROM", "Rumania (codigo ISO antiguo)", "historical", "ROU"),
    ("SER", "Serbia (codigo ISO antiguo)", "historical", "SRB"),
    ("MNT", "Montenegro (codigo ISO antiguo)", "historical", "MNE"),
    ("TMP", "Timor Oriental (codigo ISO antiguo)", "historical", "TLS"),
    ("SUD", "Sudan (codigo ISO antiguo)", "historical", "SDN"),
    # --- Territorios sin codigo ISO propio en las fuentes ---
    ("USP", "Islas menores del Pacifico (EE.UU.)", "unknown", None),
    ("BAT", "Territorio Antartico Britanico", "unknown", None),
    ("PCE", "Islas del Pacifico (antiguo territorio fideicomiso)",
     "unknown", None),
    ("NZE", "Codigo no ISO de la fuente, sin clasificar", "unknown", None),
]


def _poblar_areas() -> None:
    """Cargar ref.area: paises ISO + agregados + entidades historicas."""
    # Todo pais de ref.country es tambien un area.
    op.execute(
        "INSERT INTO ref.area (code, name, area_type, country_code) "
        "SELECT code, name, 'country', code FROM ref.country "
        "ON CONFLICT (code) DO NOTHING"
    )
    for code, name, tipo, sucesor in AREAS_NO_ISO:
        pais = f"'{sucesor}'" if sucesor else "NULL"
        nombre = name.replace("'", "''")
        op.execute(
            "INSERT INTO ref.area (code, name, area_type, country_code) "
            f"VALUES ('{code}', '{nombre}', '{tipo}', {pais}) "
            "ON CONFLICT (code) DO NOTHING"
        )


def _poblar_producto_total() -> None:
    """Anadir el agregado 'Total' al catalogo HS.

    Las matrices bilaterales de WITS se cargan a nivel producto 'Total'
    (todos los capitulos). Sin esta fila, product_code no puede tener FK
    contra ref.hs_product.
    """
    op.execute(
        "INSERT INTO ref.hs_product (code, description, level) "
        "VALUES ('Total', 'Todos los productos (agregado)', 0) "
        "ON CONFLICT (code) DO NOTHING"
    )


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area',
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('area_type', sa.String(length=20), nullable=False),
    sa.Column('country_code', sa.String(length=3), nullable=True),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['country_code'], ['ref.country.code'], ),
    sa.PrimaryKeyConstraint('code'),
    schema='ref'
    )
    op.create_index('ix_ref_area_country', 'area', ['country_code'], unique=False, schema='ref')
    op.create_index('ix_agri_prod_source', 'production', ['source_id'], unique=False, schema='agri')
    op.create_index('ix_alt_housing_country', 'housing_index', ['country_code'], unique=False, schema='alt')
    op.create_index('ix_commodity_price_source', 'price_daily', ['source_id'], unique=False, schema='commodity')
    op.create_index('ix_energy_balance_source', 'balance', ['source_id'], unique=False, schema='energy')
    op.create_index('ix_eq_estimate_source', 'analyst_estimate', ['source_id'], unique=False, schema='equity')
    op.create_index('ix_eq_balance_source', 'balance_sheet', ['source_id'], unique=False, schema='equity')
    op.create_index('ix_eq_cashflow_source', 'cash_flow', ['source_id'], unique=False, schema='equity')
    op.create_index('ix_eq_company_currency', 'company', ['currency_code'], unique=False, schema='equity')
    op.create_index('ix_eq_company_exchange', 'company', ['exchange_id'], unique=False, schema='equity')
    op.create_index('ix_eq_revision_source', 'earnings_revision', ['source_id'], unique=False, schema='equity')
    op.create_index('ix_eq_income_source', 'income_statement', ['source_id'], unique=False, schema='equity')
    op.create_index('ix_eq_idxconst_company', 'index_constituent_current', ['company_id'], unique=False, schema='equity')
    op.create_index('ix_eq_idxconst_source', 'index_constituent_current', ['source_id'], unique=False, schema='equity')
    op.create_index('ix_eq_mktindex_country', 'market_index', ['country_code'], unique=False, schema='equity')
    op.create_index('ix_eq_mktindex_exchange', 'market_index', ['exchange_id'], unique=False, schema='equity')
    op.create_index('ix_eq_price_source', 'price_daily', ['source_id'], unique=False, schema='equity')
    op.create_index('ix_fi_bond_issuer', 'bond', ['issuer_id'], unique=False, schema='fi')
    op.create_index('ix_fi_issuer_country', 'bond_issuer', ['country_code'], unique=False, schema='fi')
    op.create_index('ix_forex_pair_quote', 'currency_pair', ['quote_currency'], unique=False, schema='forex')
    op.create_index('ix_forex_rate_source', 'rate_daily', ['source_id'], unique=False, schema='forex')
    op.create_index('ix_fund_exchange', 'fund', ['exchange_id'], unique=False, schema='fund')
    op.create_index('ix_gold_idxmemb_company', 'index_membership', ['company_id'], unique=False, schema='gold')
    op.add_column('data_point', sa.Column('is_forecast', sa.Boolean(), server_default='false', nullable=False), schema='macro')
    op.create_index('ix_macro_dp_source', 'data_point', ['source_id'], unique=False, schema='macro')
    op.create_index('ix_macro_series_country', 'series', ['country_code'], unique=False, schema='macro')
    op.create_index('ix_meta_fetch_run_source', 'fetch_run', ['source_id'], unique=False, schema='meta')
    op.create_index('ix_ref_exchange_country', 'exchange', ['country_code'], unique=False, schema='ref')
    op.create_index('ix_ref_exchange_currency', 'exchange', ['currency_code'], unique=False, schema='ref')
    op.create_index('ix_ref_sector_parent', 'sector', ['parent_id'], unique=False, schema='ref')
    op.create_index('ix_trade_flow_product', 'flow', ['product_code'], unique=False, schema='trade')
    op.create_index('ix_trade_flow_source', 'flow', ['source_id'], unique=False, schema='trade')

    # --- Poblar ref.area antes de apoyar las FK de trade.flow ---
    _poblar_areas()
    _poblar_producto_total()
    op.drop_constraint(op.f('flow_reporter_code_fkey'), 'flow', schema='trade', type_='foreignkey')
    op.create_foreign_key('flow_partner_code_fkey', 'flow', 'area', ['partner_code'], ['code'], source_schema='trade', referent_schema='ref')
    op.create_foreign_key('flow_product_code_fkey', 'flow', 'hs_product', ['product_code'], ['code'], source_schema='trade', referent_schema='ref')
    op.create_foreign_key('flow_reporter_code_fkey', 'flow', 'area', ['reporter_code'], ['code'], source_schema='trade', referent_schema='ref')

    # --- Marcar como proyeccion todo punto con fecha futura ---
    op.execute(
        "UPDATE macro.data_point SET is_forecast = true "
        "WHERE date > CURRENT_DATE"
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('flow_reporter_code_fkey', 'flow', schema='trade', type_='foreignkey')
    op.drop_constraint('flow_partner_code_fkey', 'flow', schema='trade', type_='foreignkey')
    op.drop_constraint('flow_product_code_fkey', 'flow', schema='trade', type_='foreignkey')
    op.create_foreign_key(op.f('flow_reporter_code_fkey'), 'flow', 'country', ['reporter_code'], ['code'], source_schema='trade', referent_schema='ref')
    op.drop_index('ix_trade_flow_source', table_name='flow', schema='trade')
    op.drop_index('ix_trade_flow_product', table_name='flow', schema='trade')
    op.drop_index('ix_ref_sector_parent', table_name='sector', schema='ref')
    op.drop_index('ix_ref_exchange_currency', table_name='exchange', schema='ref')
    op.drop_index('ix_ref_exchange_country', table_name='exchange', schema='ref')
    op.drop_index('ix_meta_fetch_run_source', table_name='fetch_run', schema='meta')
    op.drop_index('ix_macro_series_country', table_name='series', schema='macro')
    op.drop_index('ix_macro_dp_source', table_name='data_point', schema='macro')
    op.drop_column('data_point', 'is_forecast', schema='macro')
    op.drop_index('ix_gold_idxmemb_company', table_name='index_membership', schema='gold')
    op.drop_index('ix_fund_exchange', table_name='fund', schema='fund')
    op.drop_index('ix_forex_rate_source', table_name='rate_daily', schema='forex')
    op.drop_index('ix_forex_pair_quote', table_name='currency_pair', schema='forex')
    op.drop_index('ix_fi_issuer_country', table_name='bond_issuer', schema='fi')
    op.drop_index('ix_fi_bond_issuer', table_name='bond', schema='fi')
    op.drop_index('ix_eq_price_source', table_name='price_daily', schema='equity')
    op.drop_index('ix_eq_mktindex_exchange', table_name='market_index', schema='equity')
    op.drop_index('ix_eq_mktindex_country', table_name='market_index', schema='equity')
    op.drop_index('ix_eq_idxconst_source', table_name='index_constituent_current', schema='equity')
    op.drop_index('ix_eq_idxconst_company', table_name='index_constituent_current', schema='equity')
    op.drop_index('ix_eq_income_source', table_name='income_statement', schema='equity')
    op.drop_index('ix_eq_revision_source', table_name='earnings_revision', schema='equity')
    op.drop_index('ix_eq_company_exchange', table_name='company', schema='equity')
    op.drop_index('ix_eq_company_currency', table_name='company', schema='equity')
    op.drop_index('ix_eq_cashflow_source', table_name='cash_flow', schema='equity')
    op.drop_index('ix_eq_balance_source', table_name='balance_sheet', schema='equity')
    op.drop_index('ix_eq_estimate_source', table_name='analyst_estimate', schema='equity')
    op.drop_index('ix_energy_balance_source', table_name='balance', schema='energy')
    op.drop_index('ix_commodity_price_source', table_name='price_daily', schema='commodity')
    op.drop_index('ix_alt_housing_country', table_name='housing_index', schema='alt')
    op.drop_index('ix_agri_prod_source', table_name='production', schema='agri')
    op.drop_index('ix_ref_area_country', table_name='area', schema='ref')
    op.drop_table('area', schema='ref')
    # ### end Alembic commands ###
