"""indices FK de las tablas nuevas

Revision ID: 7c4eb54b1c0c
Revises: 8d89ac814aba
Create Date: 2026-08-04 05:25:06.756199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c4eb54b1c0c'
down_revision: Union[str, Sequence[str], None] = '8d89ac814aba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_eq_factor_source', 'factor_return', ['source_id'], unique=False, schema='equity')
    op.create_index('ix_fi_crp_source', 'country_risk_premium', ['source_id'], unique=False, schema='fi')
    op.create_index('ix_re_index_source', 'price_index', ['source_id'], unique=False, schema='realestate')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_re_index_source', table_name='price_index', schema='realestate')
    op.drop_index('ix_fi_crp_source', table_name='country_risk_premium', schema='fi')
    op.drop_index('ix_eq_factor_source', table_name='factor_return', schema='equity')
    # ### end Alembic commands ###
