"""v0.4.0 deriv volatilidad y futuros, intraday multidominio

Revision ID: 495f24976494
Revises: bde127ede9f5
Create Date: 2026-08-03 21:33:54.719958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '495f24976494'
down_revision: Union[str, Sequence[str], None] = 'bde127ede9f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('futures_contract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('underlying', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('yfinance_ticker', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='deriv'
    )
    op.create_table('volatility_index',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('underlying', sa.String(length=50), nullable=True),
    sa.Column('yfinance_ticker', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='deriv'
    )
    op.create_table('price_intraday',
    sa.Column('commodity_id', sa.Integer(), nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('interval', sa.String(length=3), nullable=False),
    sa.Column('open', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('high', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('low', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('close', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodity.commodity.id'], ),
    sa.PrimaryKeyConstraint('commodity_id', 'ts', 'interval'),
    schema='commodity',
    postgresql_partition_by='RANGE (ts)'
    )
    op.create_index('ix_comm_intraday_interval_ts', 'price_intraday', ['interval', 'ts'], unique=False, schema='commodity')
    op.create_table('price_intraday',
    sa.Column('coin_id', sa.Integer(), nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('interval', sa.String(length=3), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('high', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('low', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('close', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('volume_usd', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['coin_id'], ['crypto.coin.id'], ),
    sa.PrimaryKeyConstraint('coin_id', 'ts', 'interval'),
    schema='crypto',
    postgresql_partition_by='RANGE (ts)'
    )
    op.create_index('ix_crypto_intraday_interval_ts', 'price_intraday', ['interval', 'ts'], unique=False, schema='crypto')
    op.create_table('futures_daily',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('high', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('low', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('close', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['deriv.futures_contract.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['meta.data_source.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_id', 'date'),
    schema='deriv'
    )
    op.create_index('ix_deriv_fut_contract_date', 'futures_daily', ['contract_id', 'date'], unique=False, schema='deriv')
    op.create_table('volatility_daily',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('index_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('high', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('low', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('close', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['index_id'], ['deriv.volatility_index.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['meta.data_source.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('index_id', 'date'),
    schema='deriv'
    )
    op.create_index('ix_deriv_vol_idx_date', 'volatility_daily', ['index_id', 'date'], unique=False, schema='deriv')
    op.create_table('rate_intraday',
    sa.Column('pair_id', sa.Integer(), nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('interval', sa.String(length=3), nullable=False),
    sa.Column('open', sa.Numeric(precision=14, scale=8), nullable=True),
    sa.Column('high', sa.Numeric(precision=14, scale=8), nullable=True),
    sa.Column('low', sa.Numeric(precision=14, scale=8), nullable=True),
    sa.Column('close', sa.Numeric(precision=14, scale=8), nullable=True),
    sa.ForeignKeyConstraint(['pair_id'], ['forex.currency_pair.id'], ),
    sa.PrimaryKeyConstraint('pair_id', 'ts', 'interval'),
    schema='forex',
    postgresql_partition_by='RANGE (ts)'
    )
    op.create_index('ix_forex_intraday_interval_ts', 'rate_intraday', ['interval', 'ts'], unique=False, schema='forex')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_forex_intraday_interval_ts', table_name='rate_intraday', schema='forex')
    op.drop_table('rate_intraday', schema='forex')
    op.drop_index('ix_deriv_vol_idx_date', table_name='volatility_daily', schema='deriv')
    op.drop_table('volatility_daily', schema='deriv')
    op.drop_index('ix_deriv_fut_contract_date', table_name='futures_daily', schema='deriv')
    op.drop_table('futures_daily', schema='deriv')
    op.drop_index('ix_crypto_intraday_interval_ts', table_name='price_intraday', schema='crypto')
    op.drop_table('price_intraday', schema='crypto')
    op.drop_index('ix_comm_intraday_interval_ts', table_name='price_intraday', schema='commodity')
    op.drop_table('price_intraday', schema='commodity')
    op.drop_table('volatility_index', schema='deriv')
    op.drop_table('futures_contract', schema='deriv')
    # ### end Alembic commands ###
