"""unique en crypto.coin.symbol tras fusionar duplicados

Revision ID: 81c55f8f31d8
Revises: 7c4eb54b1c0c
Create Date: 2026-08-05 13:00:23.223571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81c55f8f31d8'
down_revision: Union[str, Sequence[str], None] = '7c4eb54b1c0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'coin', ['symbol'], schema='crypto')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'coin', schema='crypto', type_='unique')
    # ### end Alembic commands ###
