"""normalizar timestamps de auditoria a timestamptz

Revision ID: e645e3e14db2
Revises: e91bf635ef50
Create Date: 2026-08-03 22:14:26.731303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e645e3e14db2'
down_revision: Union[str, Sequence[str], None] = 'e91bf635ef50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


VISTA_DIM_DATA_SOURCE = """
CREATE VIEW gold.dim_data_source AS
SELECT ds.name,
    ds.display_name,
    ds.base_url,
    ds.is_enabled,
    count(fr.id) AS total_runs,
    count(fr.id) FILTER (WHERE fr.status::text = 'success'::text)
        AS successful_runs,
    max(fr.finished_at) AS last_run,
    sum(fr.records_inserted) AS total_records
   FROM meta.data_source ds
     LEFT JOIN meta.fetch_run fr ON fr.source_id = ds.id
  GROUP BY ds.id, ds.name, ds.display_name, ds.base_url, ds.is_enabled
"""


def upgrade() -> None:
    """Upgrade schema."""

    # Los valores almacenados ya estaban en UTC (el servidor corre en
    # Etc/UTC). Fijar la zona en la sesion hace que PostgreSQL trate la
    # conversion timestamp -> timestamptz como un cambio de metadatos,
    # sin reescribir las tablas grandes (bronze.sec_companyfacts pesa
    # 9 GB y macro.data_point 1,6 GB).
    op.execute("SET LOCAL timezone TO 'UTC'")
    # Si el pipeline nocturno esta escribiendo, es preferible fallar
    # rapido y reintentar que dejar un ACCESS EXCLUSIVE en cola
    # bloqueando a todos los lectores detras.
    op.execute("SET LOCAL lock_timeout = '20s'")
    # La vista depende de meta.fetch_run.finished_at y bloquea
    # el cambio de tipo: se recrea al final.
    op.execute("DROP VIEW IF EXISTS gold.dim_data_source")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('production', 'fetched_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               schema='agri')
    op.alter_column('analyst_snapshot', 'ingested_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               schema='bronze')
    op.alter_column('api_response', 'ingested_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               schema='bronze')
    op.alter_column('constituents_snapshot', 'ingested_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               schema='bronze')
    op.alter_column('sec_companyfacts', 'ingested_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               schema='bronze')
    op.alter_column('yf_profile', 'ingested_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               schema='bronze')
    op.alter_column('profile', 'last_updated',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               schema='country')
    op.alter_column('option_snapshot', 'fetched_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               schema='deriv')
    op.alter_column('balance', 'fetched_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               schema='energy')
    op.alter_column('balance_sheet', 'fetched_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               schema='equity')
    op.alter_column('cash_flow', 'fetched_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               schema='equity')
    op.alter_column('company', 'last_updated',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               schema='equity')
    op.alter_column('income_statement', 'fetched_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               schema='equity')
    op.alter_column('data_point', 'fetched_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               schema='macro')
    op.alter_column('data_quality', 'last_assessed',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               schema='meta')
    op.alter_column('fetch_run', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               schema='meta')
    op.alter_column('fetch_run', 'finished_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               schema='meta')
    op.alter_column('transform_run', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               schema='meta')
    op.alter_column('transform_run', 'finished_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               schema='meta')
    op.alter_column('flow', 'fetched_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               schema='trade')
    # ### end Alembic commands ###


    op.execute(VISTA_DIM_DATA_SOURCE)

def downgrade() -> None:
    """Downgrade schema."""

    # Los valores almacenados ya estaban en UTC (el servidor corre en
    # Etc/UTC). Fijar la zona en la sesion hace que PostgreSQL trate la
    # conversion timestamp -> timestamptz como un cambio de metadatos,
    # sin reescribir las tablas grandes (bronze.sec_companyfacts pesa
    # 9 GB y macro.data_point 1,6 GB).
    op.execute("SET LOCAL timezone TO 'UTC'")
    # Si el pipeline nocturno esta escribiendo, es preferible fallar
    # rapido y reintentar que dejar un ACCESS EXCLUSIVE en cola
    # bloqueando a todos los lectores detras.
    op.execute("SET LOCAL lock_timeout = '20s'")
    # La vista depende de meta.fetch_run.finished_at y bloquea
    # el cambio de tipo: se recrea al final.
    op.execute("DROP VIEW IF EXISTS gold.dim_data_source")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flow', 'fetched_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               schema='trade')
    op.alter_column('transform_run', 'finished_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               schema='meta')
    op.alter_column('transform_run', 'started_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               schema='meta')
    op.alter_column('fetch_run', 'finished_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               schema='meta')
    op.alter_column('fetch_run', 'started_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               schema='meta')
    op.alter_column('data_quality', 'last_assessed',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               schema='meta')
    op.alter_column('data_point', 'fetched_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               schema='macro')
    op.alter_column('income_statement', 'fetched_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               schema='equity')
    op.alter_column('company', 'last_updated',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               schema='equity')
    op.alter_column('cash_flow', 'fetched_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               schema='equity')
    op.alter_column('balance_sheet', 'fetched_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               schema='equity')
    op.alter_column('balance', 'fetched_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               schema='energy')
    op.alter_column('option_snapshot', 'fetched_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               schema='deriv')
    op.alter_column('profile', 'last_updated',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               schema='country')
    op.alter_column('yf_profile', 'ingested_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               schema='bronze')
    op.alter_column('sec_companyfacts', 'ingested_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               schema='bronze')
    op.alter_column('constituents_snapshot', 'ingested_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               schema='bronze')
    op.alter_column('api_response', 'ingested_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               schema='bronze')
    op.alter_column('analyst_snapshot', 'ingested_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               schema='bronze')
    op.alter_column('production', 'fetched_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               schema='agri')
    # ### end Alembic commands ###

    op.execute(VISTA_DIM_DATA_SOURCE)
